version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'type/build'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]