name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: '⚠ Breaking Changes'
    label: 'type/breaking'
  - title: '🚀 New Features'
    label: 'type/feat'
  - title: '🐜 Bug Fixes'
    label: 'type/fix'
  - title: '🧰 Maintenance'
    label: 'type/chore'
  - title: '📖 Documentation'
    label: 'type/docs'
  - title: '⬆ Version Upgrades'
    label: 'type/build'
    collapse-after: 10
  - title: 'Other changes'
    collapse-after: 10

version-resolver:
  major:
    labels:
      - 'type/breaking'
  minor:
    labels:
      - 'type/feat'
  patch:
    labels:
      - 'type/fix'
      - 'type/build'
      - 'type/docs'
      - 'type/chore'
      - 'type/refactor'
      - 'type/ci'
      - 'type/style'
      - 'type/test'

exclude-labels:
  - 'skip-changelog'