#Tabs not spaces, you moron :)

name: CI for netris:relay

on:
    pull_request:
        paths:
            - "relay.Dockerfile"
            - ".github/workflows/relay.yml"
    schedule:
        - cron: 0 0 * * * # At the end of everyday
    push:
        branches: [main]
        paths:
            - "relay.Dockerfile"
            - ".github/workflows/relay.yml"
        tags:
            - v*.*.*
    release:
        types: [created]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: wanjohiryan/netris
    BASE_TAG_PREFIX: relay

jobs:
    build-docker-pr:
        name: Build image on pr
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file: relay.Dockerfile
                context: ./
                push: false
                load: true
                tags: netris:relay

    build-docker-main:
        name: Build image on merge
        if: ${{github.ref == 'refs/heads/main'}}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - 
              name: Extract Container metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.BASE_TAG_PREFIX }}
                #
                #tag on release, and a nightly build for 'dev'
                tags: |
                  type=raw,value=nightly,enable={{is_default_branch}}
                  type=ref,event=tag
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file: relay.Dockerfile
                context: ./
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}